#%RAML 1.0 AnnotationTypeDeclaration
properties:
  Anno:
    description: to define custom properties for a RAML API specification
    default: get
  conroller:
    properties:
      protocol:
        description: HTTPS
      url: 
        description: 
     