#%RAML 1.0 NamedExample
#  "CategoriesExample": 
  [
      {
      "PcategoryID":10,
      "name":"mobiles"
      },
      {
      "PcategoryID":11, 
      "name":"laptops"
      },
      {
      "PcategoryID":12, 
      "name":"home electronics" 
      },
      {
      "PcategoryID":13,
       "name":"mouse"
      },
      {
      "PcategoryID":14, 
      "name":"mobile accessories"
      },
      {
      "PcategoryID":15,
       "name":"laptop skins"
      },
      {
      "PcategoryID":16,
       "name":"laptop covers"
      }

  ]