#%RAML 1.0 DocumentationItem
title: Craft Online API
content: Craft Online Shoping root file
         Fragments
          Data Types
          Examples
          Security
          Trait
          resource type
          