#%RAML 1.0 NamedExample

# "OrdersExample":
[
    {
    "orderID": 101,
    "userid": 001,
    "name": "Tmobile" 
    },
    {
    "orderID": 102,
    "userid": 002,
    "name": "iPhone" 
    },
    {
    "orderID": 103,
    "userid": 003,
    "name": "samsung" 
    },
    {
    "orderID": 104,
    "userid": 004,
    "name": "Nokia" 
    },
    {
    "orderID": 105,
    "userid": 005,
    "name": "Motorolla" 
    },
    {
    "orderID": 106,
    "userid": 006,
    "name": "verizon" 
    }

]