#%RAML 1.0 NamedExample
# productexample:
  {
    "productId":1,
    "name":"Hp pavilione laptop",
    "description":"Hp laptop",
    "original price":1000,
    "offer":{
      "offerPrice":1000,
      "offerValidUntil":123456789
            },
    "brandName":"HP",
    "image1":"jpeg",
    "image2":"jpeg",
    "image3":"jpeg"
  }