#%RAML 1.0 NamedExample

# "productsexample": 
[
    {
      "productId":1,
      "name":"Hp pavilione laptop",
      "description":"Hp laptop",
      "original price":1000,
      "offer":{
        "offerPrice":1000,
        "offerValidUntil":123456789
              },
      "brandName":"HP",
      "image1":"jpeg",
      "image2":"jpeg",
      "image3":"jpeg"  
    },

      {
      "productId":2,
      "name":"Macbook pro laptop",
      "description":"Apple laptop",
      "original price":3000,
      "offer":{
        "offerPrice":3000,
        "offerValidUntil":123456781
              },
      "brandName":"Apple",
      "image1":"jpeg",
      "image2":"jpeg",
      "image3":"jpeg"
      },

      {
      "productId":3,
      "name":"Macbook pro laptop",
      "description":"Apple laptop",
      "original price":2000,
      "offer":{
        "offerPrice":2000,
        "offerValidUntil":123456782
              },
      "brandName":"Apple",
      "image1":"jpeg",
      "image2":"jpeg",
      "image3":"jpeg"
      },
  ]