#%RAML 1.0 NamedExample

#  "UsersExample":
[
    {
    "userID":001,
    "name":"Mr.x" 
    },
    {
    "userID":002,
    "name":"Ms.Y" 
    },
    {
    "userID":003,
    "name":"Mr.Z" 
    },
    {
    "userID":004,
    "name":"Ms.P"
    },
    {
    "userID":005,
    "name":"Mr.Q" 
    },
    {
    "userID":006,
    "name":"Mr.V" 
    }
]